#!/bin/sh

sh_menu () {
	# -l 3 because there are 3 monitor options.
	ls ~/.config/monitor/modes | dmenu -p "Monitor Mode:" -l 3
}

mode=$(sh_menu)

# Execute monitor mode.
~/.config/monitor/modes/$mode

# Update background resolution
nitrogen --restore
