#!/bin/bash

i3lock \
--color 282c34 \
--clock \
--ring-width 2  \
--inside-color 00000000  \
--ring-color 8bcd5b \
--keyhl-color c75ae8 \
--bshl-color f65866 \
--ringwrong-color f65866 \
--insidever-color 00000000  \
--ringver-color c75ae8 \
--insidewrong-color 00000000 \
--line-color 00000000  \
--time-color f8f8f2  \
--date-color f8f8f2  \
--verif-color f8f8f2  \
--wrong-color f8f8f2  \
--time-font Poppins  \
--date-font Poppins  \
